services:
  - type: web
    name: baixasom-back
    env: node
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
